<template>
  <section id="model-architecture" class="model-architecture model-arch-bg">
    <div class="container">
      <!-- <div class="model-arch-label">Model architecture</div> -->
      <h2 class="model-arch-title">Automatic Annotate Any 360 Video Pipeline</h2>
      <p class="model-arch-desc">
        Shown below are some sample groups including the raw video, the annotations generated by our pipeline, and the manually modified annotations.
      </p>
      <!-- <p class="model-arch-desc">
        SAM 2's streaming architecture—which processes video frames one at a time—is also a natural generalization of SAM to the video domain. When SAM 2 is applied to images, the memory module is empty and the model behaves like SAM.
      </p> -->
    </div>

    <div class="carousel results-carousel">
      <button @click="prevGroup" class="carousel-arrow left-arrow">←</button>
      <div class="video-group">
        <div 
          class="box m-5"
          v-for="(item, index) in currentGroup"
          :key="index"
        >
          <video 
            :src="item.src" 
            :alt="item.altText"
            width="80%"
            autoplay loop muted playsinline controls
          ></video>
          <p>{{ item.description }}</p>
        </div>
      </div>
      <button @click="nextGroup" class="carousel-arrow right-arrow">→</button>
    </div>

  </section>
</template>

<script setup>
import { ref, computed } from 'vue';

const carouselItems = ref([
  {
    src: "/Leader360_Homepage_VUE/assets/videos/anno1/raw1.mp4",
    altText: "raw1",
    description: "Raw video"
  },
  {
    src: "/Leader360_Homepage_VUE/assets/videos/anno1/manual1.mp4",
    altText: "Manual1",
    description: "Manual annotation"
  },
  {
    src: "/Leader360_Homepage_VUE/assets/videos/anno1/pipe1.mp4",
    altText: "Auto1",
    description: "Pipeline annotation"
  },
  {
    src: "/Leader360_Homepage_VUE/assets/videos/anno2/raw2.mp4",
    altText: "raw2",
    description: "Raw video"
  },
  {
    src: "/Leader360_Homepage_VUE/assets/videos/anno2/manual2.mp4",
    altText: "Manual2",
    description: "Manual annotation"
  },
  {
    src: "/Leader360_Homepage_VUE/assets/videos/anno2/pipe2.mp4",
    altText: "Auto2",
    description: "Pipeline annotation"
  }
]);

const currentIndex = ref(0);
const videosPerGroup = 3;

const currentGroup = computed(() => {
  const start = currentIndex.value * videosPerGroup;
  return carouselItems.value.slice(start, start + videosPerGroup);
});

function prevGroup() {
  if (currentIndex.value > 0) {
    currentIndex.value--;
  }
}

function nextGroup() {
  if ((currentIndex.value + 1) * videosPerGroup < carouselItems.value.length) {
    currentIndex.value++;
  }
}
</script>

<style scoped>
.model-architecture {
  max-width: 1200px;
  margin: 0 auto;
  padding: 40px 0;
}
.model-arch-label {
  font-size: 1.2em;
  color: #42b883;
  margin-bottom: 8px;
}
.model-arch-title {
  font-size: 2em;
  margin: 0 0 16px 0;
}
.model-arch-desc {
  font-size: 1.2em;
  color: #555;
  margin-bottom: 16px;
}
.model-arch-bg {
  background: #f7f8fa;
}
.carousel {
  display: flex;
  align-items: center;
}
.carousel-arrow {
  background: none;
  border: none;
  font-size: 2em;
  cursor: pointer;
  color: #555;
}
.video-group {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
  gap: 5px
}
.box {
  flex: 1 0 40%;  /* 每个视频占据30%的宽度 */
  margin: 1px;   /* 添加间距 */
  text-align: center;
  /* gap: 5px */
}

</style> 